Repository pytest-dev/pytest-testinfra, pull requests merged in 2020-11, with the labels that each got.

#577 Rename project to pytest-infra
  setup.cfg
Labels: ci

#581 Migrate from travis to github
  .github/workflows/tox.yml
  .travis.yml
  test/test_modules.py
  tox.ini
Labels: ci

#586 Remove docker login from github action
  .github/workflows/tox.yml
Labels: skip-changelog

#589 Import quote() from shlex
  testinfra/backend/base.py
Labels: bug

#591 Removing Test Python 3.5 Environment
  tox.ini
Labels: skip-changelog
