Repository pytest-dev/pytest-testinfra, pull requests merged in 2023-05, with the labels that each got.

#695 Workaround Docker#42442 by using IPv4 SSH only
  test/conftest.py
Labels: bug

#686 check if key "distribution" exists
  testinfra/modules/systeminfo.py
Labels: bug

#690 Add propery Group.user_list
  testinfra/modules/group.py
Labels: feature

#688 Add File.is_executable
  test/test_modules.py
  testinfra/modules/file.py
Labels: feature

#683 Add Windows support for File and Service modules
  testinfra/modules/file.py
  testinfra/modules/service.py
Labels: help wanted, windows
