Repository pytest-dev/pytest-testinfra, pull requests merged in 2023-08, with the labels that each got.

#708 Retry SSH on ConnectionResetError
  testinfra/backend/paramiko.py
Labels: bug

#713 Add support for the SSH ControlPath connection sharing option
  testinfra/backend/ssh.py
  testinfra/utils/ansible_runner.py
Labels: feature

#726 Fix output of error message
  testinfra/utils/ansible_runner.py
Labels: bug

#724 Ansible: Fix for missing group names in get_variables()
  test/test_backends.py
  test/test_modules.py
  testinfra/utils/ansible_runner.py
Labels: bug, ansible
