Repository pytest-dev/pytest-testinfra, pull requests merged in 2023-11, with the labels that each got.

#740 Extend list of valid suffixes for systemd units
  testinfra/modules/service.py
Labels: bug

#738 Define types for plugin.py
  testinfra/plugin.py
Labels: typing

#741 Add Service.exists
  testinfra/modules/service.py
Labels: enhancement

#722 Make CommandResult a dataclass
  testinfra/backend/ansible.py
  testinfra/backend/base.py
  testinfra/backend/salt.py
  testinfra/backend/winrm.py
Labels: typing
